on:
  push:
    branches: [develop]

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: calculate version
      id: calculate-version
      uses: bitshifted/git-auto-semver@v1
      with:
        main_branch: develop
        create_tag: true

    - name: Use version
      run: |
        echo "Calculated version: ${{ steps.calculate-version.outputs.version-string }}"